name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    name: GHA-CI-ARGO-CD
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2